### ISSUE TITLE
Desired easter egg: Respond sophisticatedly to humans typing "meow"s.

### ISSUE THREAD

**Issue by alcinnz** [woutervdijke/CatGPT#1]
It could have a sampling of texts pondering deep philosophical questions!

**Comment by woutervdijke** [comment]
😺 fun idea. Any suggestions for replies are welcome

**Comment by alcinnz** [comment]
How about taking text from this page?
https://overtimephilosophy.com/the-10-deepest-philosophical-questions-and-the-best-answers/

**Comment by woutervdijke** [comment]
Added in 8f2e6ca3fbb139c9bd4354ceeb8565fb0fae7bcc 😸

**Comment by Subroutine7901** [comment]
Came across this egg when meowing to it, very, very cool.
Also, kitty.
